nitncwind-org/v3

public/data/concours.json, public/data/ensemble.json, src/components/F3.vue, src/views/Concours.vue
=> コンクール情報のJsonフォーマットを変更 #5

public/404.html
=> 無限リダイレクトを修正

src/components/Footer.vue
ページコンテンツの一番下に表示されて，ページコンテンツが少なくても画面の一番下になる
=> フッターの位置を調整

package-lock.json, package.json, src/components/Header.vue, src/plugins/vuetify.js, src/router/index.js, src/views/About.vue, src/views/Concerts.vue, src/views/Concours.vue, src/views/Ensemble.vue, src/views/Home.vue, src/views/Link.vue, src/views/Winds.vue
吹奏楽コンクールとアンサンブルコンテストのページをコンクールのサブページにした
=> コンテスト実績の表示方法を変更

src/router/index.js, src/views/404.vue
=> 404ページを追加 #26

src/router/index.js
=> routerエントリにEnsembleが二つあるのを修正

src/components/F1.vue, src/views/Concerts.vue, src/views/Home.vue
=> コンサート情報の表示判定を日付のみで判定するように変更 #46

src/router/index.js
=> /concoursにアクセスしたときに404が表示されるように変更 #62

src/lib/csv.js, src/views/Ensemble.vue, src/views/Link.vue, src/views/Winds.vue
=> Link集をCSVから読み込むように変更

src/lib/csv.js, src/views/Ensemble.vue, src/views/Winds.vue
=> コンクール実績のCSV読み込みを修正

.github/workflows/gh-pages.yml, public/robots.txt
=> robots.txtの追加

src/components/F1.vue, src/views/Concerts.vue
=> コンサート情報をCSVで読み込むように変更 #83

src/components/F1.vue
fix/design/color_infobox#94の修正箇所に取り掛かる前に，F1のレイアウトの修正（design/concert_info#82のブランチ）をdesign/developにマージしていただけますか？
@NAKNAO-nnct
=> F1のレイアウト修正

src/components/F1.vue, src/router/index.js, src/views/ConcertsDetail.vue
=> コンサートページの動的ページを実装 #97

public/index.html, src/App.vue, src/components/Footer.vue, src/components/Header.vue, src/components/Title.vue, src/plugins/vuetify.js, src/views/Home.vue
@NAKNAO-nnct 
こんな感じのデザインに直しました． design/developへのマージお願いします．
=> [design] ヘッダーとフッターのデザイン変更 #70

src/views/Home.vue
=> TOPページのコンサート情報をCSVから読むように変更 #105

src/components/F1.vue, src/lib/csv.js, src/router/index.js, src/views/About.vue, src/views/ConcertsDetail.vue, src/views/Ensemble.vue, src/views/Home.vue, src/views/Link.vue, src/views/Winds.vue
Reverts nitncwind-org/gen3#110
=> Revert "Revert "Feature/design""

src/views/Contact.vue
=> お問い合わせ内容を更新 #10

src/views/Concerts.vue, src/views/ConcertsDetail.vue, src/views/Home.vue
=> 入場料が0円の時に表示が無料になるように修正 #116

src/views/ConcertsDetail.vue
=> 指定されたコンサートページIDが存在しないとき/404にリダイレクトするように変更 #125

src/views/Link.vue
=> Link集のリンクを別タブで開くように変更 #56

src/views/Contact.vue
=> お問い合わせフォームの詳細入力欄をrequiredに変更 #133

.github/workflows/gh-pages.yml, src/config/development.js, src/config/production.js, src/config/url.js, src/lib/csv.js, src/views/About.vue, src/views/Concerts.vue, src/views/ConcertsDetail.vue, src/views/Ensemble.vue, src/views/Home.vue, src/views/Link.vue, src/views/Winds.vue
=> productionビルドの時にAPIのURLが変更される機能を追加 #132

.github/workflows/gh-pages.yml, package.json
=> ビルドコマンドを修正 #138

.env.development, .env.production, src/config/development.js, src/config/production.js, src/config/url.js
=> .envファイルからURL設定を読み込むように変更 #132

.env.development, .env.prerelease, .env.production, package.json, src/config/development.js, src/config/production.js, src/config/url.js
=> prerelease用のconfigを追加#137

.env.development, .env.production, src/config/url.js, src/views/Contact.vue
=> お問い合わせフォームのPOST先URLをenvで管理するように変更 #142

src/components/Header.vue, src/router/index.js, src/views/News.vue, src/views/NewsDetail.vue
=> NewsページとNewsを表示するバナーを追加 #135

src/components/Header.vue, src/plugins/vuetify.js
=> メニューバーの影を削除

src/components/Header.vue
=> メニューを全画面で表示するように修正

src/views/Concerts.vue
=> コンサート一覧ページ

src/components/Header.vue
=> バナーのデザインを変更

src/views/Home.vue
=> 次回の演奏会がない時，"演奏会の予定はありません"を表示するように変更 #163

src/views/NewsDetail.vue
=> ニュース詳細ページ 

package-lock.json, package.json
#167 
Linterのレベルを上げた
commit前にLinterが自動で走るように設定
=> Linterの設定を変更 #167

public/index.html
=> ban_ieのHTMLを修正 #174

.env.development, .env.prerelease, .env.production, src/main.js
Vueで読み込む環境変数は接頭辞に"VUE_APP_"が必要
#184
=> 環境変数からIDを取得できていない問題を修正

src/views/Contact.vue
=> [fix] 送信エラー時の挙動修正

package-lock.json, package.json
=> リリース v3.0.3

.github/workflows/codeql-analysis.yml, .github/workflows/gh-pages.yml, .github/workflows/manualDeploy.yml
Actionsで使用しているimageが古いので更新
- ubuntu-latestでworkflowを実行するように変更
- checkoutをv3に更新
=> Actionsのworkflowを更新

package-lock.json, package.json
=> Revert "Bump vuetify from 2.2.22 to 2.6.10"
